name: 'Setup Gradle'
description: 'Sets up Java and Gradle for Kotlin/Java projects.'
runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: ./.github/actions/setup-java

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1 (read below)
      with:
        add-job-summary-as-pr-comment: on-failure

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions (i.e. setup-gradle) to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.
