name: 'Setup Java'
description: 'Sets up Java 21 for Kotlin/Java projects.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
