name: Auto Assign Author

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  workflow_call: # Allows this workflow to be called from other workflows.
  issues:
    types: [ opened, reopened ]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
