name: Dependency Submission

on:
  release:
    types: [ published ]

  # This allows manual triggering of the workflow from the GitHub UI.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
