name: Dependency Submission

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  workflow_call: # Allows this workflow to be called from other workflows.

permissions:
  contents: write
  packages: read   # ⬅️ Required for Gradle to fetch from GitHub Packages

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    env: # Expose secrets to Gradle
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
