name: Unit Tests

on:
  workflow_call:

jobs:
  unit-test-job:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Setup Gradle takes care of gradle caching & dependency graph reporting
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Unit tests
        run: ./gradlew check

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unit-Test-Reports
          path: |
            **/build/test-results/test/

      - name: Create Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Test Report
          reporter: java-junit
          path: |
            **/build/test-results/test/*.xml
