name: Publish Release

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  push:
    branches:
      - main

jobs:
  version-tag:
    uses: ./.github/workflows/publish/version-tag.yml

  dokka:
    uses: ./github/workflows/publish/dokka.yml
    needs: [version-tag]

  dependency-submission:
    uses: ./.github/workflows/publish/dependency-submission.yml
    needs: [version-tag]

  codeql:
    uses: ./.github/workflows/publish/codeql.yml
    needs: [version-tag]

  github-packages:
    uses: ./.github/workflows/publish/github-packages.yml
    needs: [version-tag, dokka, dependency-submission, codeql]
