# Read this: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle
name: Publish to Maven Central & GitHub Packages

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  workflow_call: # Allows this workflow to be called from other workflows.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Ensure running on main branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "This workflow can only be run from the main branch."
          exit 1

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-gradle

      - name: Cache Gradle build
        uses: ./.github/actions/cache-gradle

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
