name: Publish Dokka

# Controls when the workflow will run
on:
  # Triggers the workflow on release
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-dokka:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-gradle

      - name: Cache Gradle build
        uses: ./.github/actions/cache-gradle

      - name: Build documentation
        run: ./gradlew dokkaGenerate

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: build/dokka/html
