name: Pull Request CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Setup Gradle takes care of gradle caching & dependency graph reporting
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: on-failure # Valid values are 'never' (default), 'always', and 'on-failure'

      - name: Execute Gradle build
        run: ./gradlew build

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/job-unit-tests.yml

  automerge-dependabot-job:
    name: Automerge Dependabot
    needs: [ build, unit-tests ] # After these jobs: if one of them fails, it won't merge the PR.
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
