name: Pull Request

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

permissions:
  pull-requests: write # Used by: assign-author
  packages: read # Used by: build and unit-tests to enable dependencies from Github Packages

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/build.yml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
