name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-assign-author:
    uses: ./.github/workflows/auto-assign-author.yml

  setup-java-gradle:
    uses: ./.github/workflows/setup-gradle.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: setup-java-gradle

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: build

  automerge-dependabot-job:
    # Only run for PRs created by dependabot after other all checks pass (i.e. build & unit tests)
    needs: [ build, unit-tests ]
    uses: ./.github/workflows/automerge-dependabot.yml
