name: Pull Request

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-assign-author:
    uses: ./.github/workflows/auto-assign-author.yml

  build:
    uses: ./.github/workflows/build.yml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: build

  version-bump:
    uses: ./.github/workflows/version-bump.yml

  # Only run for PRs created by dependabot after other all checks pass (i.e. build & unit tests)
  automerge-dependabot-job:
    uses: ./.github/workflows/automerge-dependabot.yml
    needs: [ build, unit-tests ]
