name: Unit Tests

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  workflow_call: # Allows this workflow to be called from other workflows.

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-gradle

      - name: Run Unit Tests
        run: ./gradlew check

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unit-Test-Reports
          path: |
            **/build/test-results/test/

      - name: Create Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Test Report
          reporter: java-junit
          path: |
            **/build/test-results/test/*.xml
